apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend-pod
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_HOST
            value: mysql-svc
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DB
            value: db_example
          - name: MYSQL_PASS
            value: "123456"
  selector:
    matchLabels:
      type: frontend